import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { isIndex, nocache } from "@/constants/constants";
export const dynamic = "force-dynamic";
import Provider from "./provider";

const archivo = Archivo({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

const creatoDisplay = localFont({
  src: [
    {
      path: "../public/fonts/CreatoDR.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/CreatoDM.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/CreatoDB.woff2",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-creato",
  display: "swap", // optional for performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: isIndex,
    nocache: nocache,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.className} ${creatoDisplay.className} antialiased`}
      >
          <Provider>{children}</Provider>
      </body>
    </html>
  );
}
